url: "https://artandsuffering.com"

permalink: /:year/:month/:day/:title:output_ext

sass:
    sass_dir: _sass
    
defaults:
  -
    scope:
      path: ""
      type: "posts"
    values:
      last-modified: "0000-00-00"